---
fixtures:
  repositories:
    facts: 'https://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    provision: 'https://github.com/puppetlabs/provision.git'
    bootstrap: "https://github.com/puppetlabs/puppetlabs-bootstrap"
    puppet_conf: "https://github.com/puppetlabs/puppetlabs-puppet_conf"
    deploy_pe: 'https://github.com/jarretlavallee/puppet-deploy_pe.git'
    ruby_task_helper: "https://github.com/puppetlabs/puppetlabs-ruby_task_helper"
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    pe_tune: "https://github.com/tkishel/pe_tune.git"
    puppet_metrics_collector: "https://github.com/puppetlabs/puppetlabs-puppet_metrics_collector.git"
    inifile: 'https://github.com/puppetlabs/puppetlabs-inifile.git'
